### ISSUE TITLE
As a sandbox user, I need a hosted ChefServer

### ISSUE THREAD

**Issue by pburkholder** [18F/azure-jenkins2-2016#3]
Punt on the question of ChefServer install and focus on delivering Jenkins value.

Get a hosted Chef account for peter.burkholder@gsa.com, share with Clint.

**Comment by pburkholder** [comment]
Created account at manage.chef.io for peterburkholdergsa (peter.burkholder@gsa.gov) and created an `org`: azjen2.

**Comment by pburkholder** [comment]
@ctro Could you please visit https://manage.chef.io and create an account for yourself? Then I can invite you to the Chef org...

**Comment by ctro** [comment]
@pburkholder I have an account at : clinton.troxel@gsa.gov

**Comment by pburkholder** [comment]
Clint is working, so done.
